#!/usr/bin/env python3
"""Generates `tests/windows.cairo` (the window probes of every layout) from the fixtures'
boundaries, and turns snforge's step counts of those probes into the tables of
`docs/research/07-split-game-step.md`.

    python3 crates/slingfall_split/scripts/windows.py gen
    python3 crates/slingfall_split/scripts/heavy.py snforge test steps_ --detailed-resources \\
        > steps.log            # one layout at a time: `steps_d_`, `steps_setup_`, ...
    python3 crates/slingfall_split/scripts/windows.py table steps.log [more.log ...]

A probe `steps_<layout>_<case>_<start>_<end>` plays ticks `start..end` of `case` in one chunk of
the layout's world class from main's state at `start` and checks main's state at `end`;
`steps_setup_<case>_<start>_<end>` does the same work without the chunk call. A window's steps are
the difference. `table` prints, per layout and case, the steps of each window, per tick (flight:
ticks 0-40; impact: the window of the first contact), of the shot, and the greedy packing of the
windows into transactions of at most `TX_MAX` steps.

Python 3 standard library only.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]
FIXTURES = PACKAGE / "fixtures"
OUT = PACKAGE / "tests" / "windows.cairo"
TX_MAX = 10_000_000

# probe prefix: world class (docs/research/07-split-game-step.md, "Layouts").
LAYOUTS = {
    "a": "LayoutA",
    "b": "LayoutB",
    "c": "LayoutC",
    "d": "LayoutD",
    "e": "LayoutE",
}
# The window holding the first contact of each case (the impact figure).
IMPACT = {"reference": (80, 90), "owner": (40, 50)}

HEADER = '''//! Probes (generated by `scripts/windows.py gen`, do not edit): each layout plays one window of
//! a reference shot in one chunk from main's state at its start and must end on main's state at
//! its end, bit for bit; `steps_setup_*` is the same test without the chunk call (its steps are
//! subtracted).

use crate::harness::{window, window_setup};
'''


def bounds(case: str) -> list[int]:
    ticks = sorted(int(p.stem.split("_")[1]) for p in (FIXTURES / case).glob("state_*.txt"))
    return ticks


def gen() -> None:
    out = [HEADER]
    for case in sorted(p.name for p in FIXTURES.iterdir() if p.is_dir()):
        ticks = bounds(case)
        last = ticks[-1]
        for start, end in zip(ticks, ticks[1:]):
            over = "true" if end == last else "false"
            tag = f"{case}_{start:03}_{end:03}"
            out.append(f"\n#[test]\nfn steps_setup_{tag}() {{\n"
                       f"    window_setup(\"{case}\", {start}, {end}, {over});\n}}\n")
            for prefix, layout in LAYOUTS.items():
                out.append(f"\n#[test]\nfn steps_{prefix}_{tag}() {{\n"
                           f"    window(\"{layout}\", \"{case}\", {start}, {end}, {over});\n}}\n")
    OUT.write_text("".join(out))
    print(f"wrote {OUT.relative_to(PACKAGE)}", file=sys.stderr)


PASS = re.compile(r"^\[PASS\] \S*::windows::steps_(\w+?)_(\w+)_(\d{3})_(\d{3}) ")
STEPS = re.compile(r"^\s+steps: (\d+)")


def parse(paths: list[str]) -> dict:
    """-> {(layout, case, start, end): steps} of the passing probes."""
    res = {}
    for path in paths:
        key = None
        for line in Path(path).read_text().splitlines():
            m = PASS.match(line)
            if m:
                key = (m.group(1), m.group(2), int(m.group(3)), int(m.group(4)))
                continue
            s = STEPS.match(line)
            if s and key:
                res[key] = int(s.group(1))
                key = None
    return res


def fmt(n: float) -> str:
    return f"{n:,.0f}"


def table(paths: list[str]) -> None:
    probes = parse(paths)
    setup = {(c, s, e): v for (l, c, s, e), v in probes.items() if l == "setup"}
    rows = defaultdict(dict)
    for (layout, case, start, end), steps in probes.items():
        if layout != "setup" and (case, start, end) in setup:
            rows[(layout, case)][(start, end)] = steps - setup[(case, start, end)]
    for (layout, case), windows in sorted(rows.items()):
        ticks = bounds(case)
        expected = list(zip(ticks, ticks[1:]))
        missing = [w for w in expected if w not in windows]
        total = sum(windows.values())
        print(f"\n#### layout ({layout}), {case}\n")
        print("| window | steps | per tick |")
        print("|---|--:|--:|")
        for (start, end) in expected:
            if (start, end) in windows:
                v = windows[(start, end)]
                print(f"| {start}-{end} | {fmt(v)} | {fmt(v / (end - start))} |")
        flight = windows.get((0, 40))
        impact = windows.get(IMPACT.get(case, (0, 0)))
        print(f"\nshot: {fmt(total)} steps{' (incomplete: ' + str(missing) + ')' if missing else ''}; "
              f"flight {fmt(flight / 40) if flight else 'n/a'} per tick; impact window "
              f"{IMPACT.get(case)} {fmt(impact / 10) if impact else 'n/a'} per tick")
        # Greedy packing of whole windows into transactions of at most TX_MAX steps.
        txs, current, first = [], 0, None
        for (start, end) in expected:
            v = windows.get((start, end))
            if v is None:
                break
            if current and current + v > TX_MAX:
                txs.append((first, start, current))
                current, first = 0, None
            if first is None:
                first = start
            current += v
        if first is not None:
            txs.append((first, expected[-1][1] if not missing else start, current))
        print("transactions: " + "; ".join(f"{a}-{b}: {v / 1e6:.2f}M" for a, b, v in txs)
              + (" (a window over the limit)" if any(v > TX_MAX for _, _, v in txs) else ""))


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("gen", "table"):
        sys.exit(__doc__)
    if sys.argv[1] == "gen":
        gen()
    else:
        table(sys.argv[2:])


if __name__ == "__main__":
    main()
