#!/usr/bin/env python3
"""Generates `tests/windows.cairo` (the window probes of every layout) from the fixtures'
boundaries, and turns snforge's step counts of those probes into the tables of
`docs/research/07-split-game-step.md`.

    python3 crates/slingfall_split/scripts/windows.py gen
    python3 crates/slingfall_split/scripts/heavy.py snforge test steps_ --detailed-resources \\
        > steps.log            # one layout at a time: `steps_d_`, `steps_setup_`, ...
    python3 crates/slingfall_split/scripts/windows.py table steps.log [more.log ...]

The probes (`tests/windows_<case>.cairo`, `tests/transactions.cairo`, `#[ignore]`: heavy; `run`
includes them): a probe `steps_<layout>_<case>_<start>_<end>` plays ticks `start..end` of `case` in one chunk of
the layout's world class from main's state at `start` and checks main's state at `end`;
`steps_setup_<case>_<start>_<end>` does the same work without the chunk call. A window's steps are
the difference. `table` prints, per layout and case, the steps of each window, per tick (flight:
ticks 0-40; impact: the window of the first contact), of the shot, and the greedy packing of the
windows into transactions of at most `TX_MAX` steps.

Python 3 standard library only.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]
FIXTURES = PACKAGE / "fixtures"
TESTS = PACKAGE / "tests"
TX_MAX = 10_000_000

# probe prefix: world class (docs/research/07-split-game-step.md, "Layouts"). (a), (c), (d), (f) are
# `crate::probes` (feature `probes`): run them with `snforge test --features probes`.
LAYOUTS = {
    "a": "LayoutA",
    "b": "FallbackGame",
    "c": "LayoutC",
    "d": "LayoutD",
    "e": "WorldClass",
    "f": "LayoutF",
}
# The window holding the first contact of each case (the impact figure).
IMPACT = {"reference": (80, 90), "owner": (40, 50)}

HEADER = '''//! Probes (generated by `scripts/windows.py gen`, do not edit): each layout plays one window of
//! a reference shot in one chunk from main's state at its start and must end on main's state at
//! its end, bit for bit; `steps_setup_*` is the same test without the chunk call (its steps are
//! subtracted).

use crate::harness::{window, window_main, window_setup};
'''


# The transactions of the chain (`slingfall_split::chain::SplitChain`) measured one by one:
# layout prefix -> case -> tick boundaries (from the greedy packing of the window probes).
TXS = {
    "b": {"owner": [0, 40, 60, 80, 100, 120, 140, 151], "reference": [0, 50, 80, 90, 107]},
    "e": {"owner": [0, 60, 80, 110, 140, 151], "reference": [0, 90, 107]},
}
TX_OUT = PACKAGE / "tests" / "transactions.cairo"
TX_HEADER = '''//! Probes (generated by `scripts/windows.py gen`, do not edit): the transactions of the chain
//! (`slingfall_split::chain::SplitChain`) one by one: `init`, each `step_chunk` of the schedule
//! (`scripts/windows.py` `TXS`) from main's state and checked against main's, `outputs`;
//! `steps_txsetup_*` is the same work without the transaction (subtracted).

use crate::chain::{tx_chunk, tx_init, tx_outputs, tx_setup};
'''


def gen_tx() -> None:
    out = [TX_HEADER]
    setups = set()
    for prefix, cases in TXS.items():
        layout = LAYOUTS[prefix]
        for case, ticks in cases.items():
            last = ticks[-1]
            tests = [(f"txinit{prefix}", 0, 0, f"tx_init(\"{layout}\", \"{case}\")"),
                     (f"txout{prefix}", last, last, f"tx_outputs(\"{layout}\", \"{case}\", {last})")]
            for start, end in zip(ticks, ticks[1:]):
                over = "true" if end == last else "false"
                tests.append((f"tx{prefix}", start, end,
                              f"tx_chunk(\"{layout}\", \"{case}\", {start}, {end}, {over})"))
            for name, start, end, call in tests:
                tag = f"{case}_{start:03}_{end:03}"
                if (case, start, end) not in setups:
                    setups.add((case, start, end))
                    out.append(f"\n#[test]\n#[ignore]\nfn steps_txsetup_{tag}() {{\n"
                               f"    tx_setup(\"{case}\", {start}, {end});\n}}\n")
                out.append(f"\n#[test]\n#[ignore]\nfn steps_{name}_{tag}() {{\n    {call};\n}}\n")
    TX_OUT.write_text("".join(out))
    print(f"wrote {TX_OUT.relative_to(PACKAGE)}", file=sys.stderr)


def bounds(case: str) -> list[int]:
    ticks = sorted(int(p.stem.split("_")[1]) for p in (FIXTURES / case).glob("state_*.txt"))
    return ticks


def gen() -> None:
    """`tests/windows_<case>.cairo`, one file per case (the 800-line budget of a file)."""
    for case in sorted(p.name for p in FIXTURES.iterdir() if p.is_dir()):
        out = [HEADER]
        ticks = bounds(case)
        last = ticks[-1]
        for start, end in zip(ticks, ticks[1:]):
            over = "true" if end == last else "false"
            tag = f"{case}_{start:03}_{end:03}"
            out.append(f"\n#[test]\n#[ignore]\nfn steps_setup_{tag}() {{\n"
                       f"    window_setup(\"{case}\", {start}, {end}, {over});\n}}\n")
            out.append(f"\n#[test]\n#[ignore]\nfn steps_m_{tag}() {{\n"
                       f"    window_main(\"{case}\", {start}, {end}, {over});\n}}\n")
            for prefix, layout in LAYOUTS.items():
                out.append(f"\n#[test]\n#[ignore]\nfn steps_{prefix}_{tag}() {{\n"
                           f"    window(\"{layout}\", \"{case}\", {start}, {end}, {over});\n}}\n")
        path = TESTS / f"windows_{case}.cairo"
        path.write_text("".join(out))
        print(f"wrote {path.relative_to(PACKAGE)}", file=sys.stderr)


PASS = re.compile(r"^\[PASS\] \S*::(?:windows_\w+|transactions)::steps_(\w+?)_(\w+)_(\d{3})_(\d{3}) ")
STEPS = re.compile(r"^\s+steps: (\d+)")


def parse(paths: list[str]) -> dict:
    """-> {(layout, case, start, end): steps} of the passing probes."""
    res = {}
    for path in paths:
        key = None
        for line in Path(path).read_text().splitlines():
            m = PASS.match(line)
            if m:
                key = (m.group(1), m.group(2), int(m.group(3)), int(m.group(4)))
                continue
            s = STEPS.match(line)
            if s and key:
                res[key] = int(s.group(1))
                key = None
    return res


def fmt(n: float) -> str:
    return f"{n:,.0f}"


def table(paths: list[str]) -> None:
    probes = parse(paths)
    setup = {(c, s, e): v for (l, c, s, e), v in probes.items() if l == "setup"}
    txsetup = {(c, s, e): v for (l, c, s, e), v in probes.items() if l == "txsetup"}
    rows = defaultdict(dict)
    for (layout, case, start, end), steps in probes.items():
        base = txsetup if layout.startswith("tx") else setup
        if layout not in ("setup", "txsetup") and (case, start, end) in base:
            rows[(layout, case)][(start, end)] = steps - base[(case, start, end)]
    for (layout, case), windows in sorted(rows.items()):
        if layout.startswith("tx"):
            print(f"\n#### {layout}, {case}: " + "; ".join(
                f"{s}-{e}: {v:,}" for (s, e), v in sorted(windows.items())))
    rows = {key: value for key, value in rows.items() if not key[0].startswith("tx")}
    for (layout, case), windows in sorted(rows.items()):
        ticks = bounds(case)
        expected = list(zip(ticks, ticks[1:]))
        missing = [w for w in expected if w not in windows]
        total = sum(windows.values())
        print(f"\n#### layout ({layout}), {case}\n")
        print("| window | steps | per tick |")
        print("|---|--:|--:|")
        for (start, end) in expected:
            if (start, end) in windows:
                v = windows[(start, end)]
                print(f"| {start}-{end} | {fmt(v)} | {fmt(v / (end - start))} |")
        flight = windows.get((0, 40))
        impact = windows.get(IMPACT.get(case, (0, 0)))
        print(f"\nshot: {fmt(total)} steps{' (incomplete: ' + str(missing) + ')' if missing else ''}; "
              f"flight {fmt(flight / 40) if flight else 'n/a'} per tick; impact window "
              f"{IMPACT.get(case)} {fmt(impact / 10) if impact else 'n/a'} per tick")
        # Greedy packing of whole windows into transactions of at most TX_MAX steps.
        txs, current, first = [], 0, None
        for (start, end) in expected:
            v = windows.get((start, end))
            if v is None:
                break
            if current and current + v > TX_MAX:
                txs.append((first, start, current))
                current, first = 0, None
            if first is None:
                first = start
            current += v
        if first is not None:
            txs.append((first, expected[-1][1] if not missing else start, current))
        print("transactions: " + "; ".join(f"{a}-{b}: {v / 1e6:.2f}M" for a, b, v in txs)
              + (" (a window over the limit)" if any(v > TX_MAX for _, _, v in txs) else ""))


LOGS = PACKAGE / "target" / "logs"


def run(prefixes: list[str]) -> None:
    """Runs the probes of each layout prefix (`setup`, `m`, `a`...) one snforge run at a time
    under the heavy-run lock, one thread, into `target/logs/<prefix>.log`."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import heavy
    import resource
    import subprocess
    LOGS.mkdir(parents=True, exist_ok=True)
    _lock = heavy.locked()
    for prefix in prefixes:
        log = LOGS / f"{prefix}.log"
        with log.open("w") as out:
            # `tx` selects every transaction probe (`steps_tx*`).
            name = f"steps_{prefix}" if prefix == "tx" else f"steps_{prefix}_"
            subprocess.run(["snforge", "test", name, "--include-ignored", "--detailed-resources",
                            "--max-threads", "1", "--features", "probes"], cwd=PACKAGE, stdout=out, stderr=subprocess.STDOUT)
        text = log.read_text()
        summary = [l for l in text.splitlines() if l.startswith(("Tests:", "[FAIL]"))]
        peak = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss / 2**20
        print(f"{prefix}: {'; '.join(summary) or 'no summary'} (peak RSS so far {peak:.1f} GiB)",
              file=sys.stderr)


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("gen", "table", "run"):
        sys.exit(__doc__)
    if sys.argv[1] == "gen":
        gen()
        gen_tx()
    elif sys.argv[1] == "run":
        run(sys.argv[2:])
    else:
        table(sys.argv[2:])


if __name__ == "__main__":
    main()
