//! Probes (generated by `scripts/windows.py gen`, do not edit): each layout plays one window of
//! a reference shot in one chunk from main's state at its start and must end on main's state at
//! its end, bit for bit; `steps_setup_*` is the same test without the chunk call (its steps are
//! subtracted).

use crate::harness::{window, window_main, window_setup};

#[test]
#[ignore]
fn steps_setup_reference_000_040() {
    window_setup("reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_m_reference_000_040() {
    window_main("reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_a_reference_000_040() {
    window("LayoutA", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_b_reference_000_040() {
    window("FallbackGame", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_c_reference_000_040() {
    window("LayoutC", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_d_reference_000_040() {
    window("LayoutD", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_e_reference_000_040() {
    window("WorldClass", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_f_reference_000_040() {
    window("LayoutF", "reference", 0, 40, false);
}

#[test]
#[ignore]
fn steps_setup_reference_040_050() {
    window_setup("reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_m_reference_040_050() {
    window_main("reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_a_reference_040_050() {
    window("LayoutA", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_b_reference_040_050() {
    window("FallbackGame", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_c_reference_040_050() {
    window("LayoutC", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_d_reference_040_050() {
    window("LayoutD", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_e_reference_040_050() {
    window("WorldClass", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_f_reference_040_050() {
    window("LayoutF", "reference", 40, 50, false);
}

#[test]
#[ignore]
fn steps_setup_reference_050_060() {
    window_setup("reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_m_reference_050_060() {
    window_main("reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_a_reference_050_060() {
    window("LayoutA", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_b_reference_050_060() {
    window("FallbackGame", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_c_reference_050_060() {
    window("LayoutC", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_d_reference_050_060() {
    window("LayoutD", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_e_reference_050_060() {
    window("WorldClass", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_f_reference_050_060() {
    window("LayoutF", "reference", 50, 60, false);
}

#[test]
#[ignore]
fn steps_setup_reference_060_070() {
    window_setup("reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_m_reference_060_070() {
    window_main("reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_a_reference_060_070() {
    window("LayoutA", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_b_reference_060_070() {
    window("FallbackGame", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_c_reference_060_070() {
    window("LayoutC", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_d_reference_060_070() {
    window("LayoutD", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_e_reference_060_070() {
    window("WorldClass", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_f_reference_060_070() {
    window("LayoutF", "reference", 60, 70, false);
}

#[test]
#[ignore]
fn steps_setup_reference_070_080() {
    window_setup("reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_m_reference_070_080() {
    window_main("reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_a_reference_070_080() {
    window("LayoutA", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_b_reference_070_080() {
    window("FallbackGame", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_c_reference_070_080() {
    window("LayoutC", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_d_reference_070_080() {
    window("LayoutD", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_e_reference_070_080() {
    window("WorldClass", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_f_reference_070_080() {
    window("LayoutF", "reference", 70, 80, false);
}

#[test]
#[ignore]
fn steps_setup_reference_080_090() {
    window_setup("reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_m_reference_080_090() {
    window_main("reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_a_reference_080_090() {
    window("LayoutA", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_b_reference_080_090() {
    window("FallbackGame", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_c_reference_080_090() {
    window("LayoutC", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_d_reference_080_090() {
    window("LayoutD", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_e_reference_080_090() {
    window("WorldClass", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_f_reference_080_090() {
    window("LayoutF", "reference", 80, 90, false);
}

#[test]
#[ignore]
fn steps_setup_reference_090_100() {
    window_setup("reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_m_reference_090_100() {
    window_main("reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_a_reference_090_100() {
    window("LayoutA", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_b_reference_090_100() {
    window("FallbackGame", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_c_reference_090_100() {
    window("LayoutC", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_d_reference_090_100() {
    window("LayoutD", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_e_reference_090_100() {
    window("WorldClass", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_f_reference_090_100() {
    window("LayoutF", "reference", 90, 100, false);
}

#[test]
#[ignore]
fn steps_setup_reference_100_107() {
    window_setup("reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_m_reference_100_107() {
    window_main("reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_a_reference_100_107() {
    window("LayoutA", "reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_b_reference_100_107() {
    window("FallbackGame", "reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_c_reference_100_107() {
    window("LayoutC", "reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_d_reference_100_107() {
    window("LayoutD", "reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_e_reference_100_107() {
    window("WorldClass", "reference", 100, 107, true);
}

#[test]
#[ignore]
fn steps_f_reference_100_107() {
    window("LayoutF", "reference", 100, 107, true);
}
