//! Probes (generated by `scripts/windows.py`, do not edit): each layout plays one window of a
//! reference shot in one chunk from main's state at its start and must end on main's state at its
//! end, bit for bit; `steps_setup_*` is the same test without the chunk call (its steps are
//! subtracted).

use crate::harness::{window, window_setup};

#[test]
fn steps_d_owner_000_040() {
    window("LayoutD", "owner", 0, 40, false);
}

#[test]
fn steps_setup_owner_000_040() {
    window_setup("owner", 0, 40, false);
}
