[package]
name = "slingfall_level"
description = "Slingfall level, inputs and outputs: Serde felt layouts and Poseidon hashes."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fixed.workspace = true
glam.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
slingfall_testing = { path = "../slingfall_testing" }

[tool]
fmt.workspace = true
scarb.workspace = true
snforge.workspace = true
