#!/usr/bin/env python3
"""Cairo-steps snapshot tooling for slingfall (adapted from rapier-cairo's `scripts/gas.py`).

Cairo steps are the budget (docs/DESIGN.md D10). Every test named `steps_*` is a step probe:
snforge reports the Cairo steps it ran (`--tracked-resource cairo-steps --detailed-resources`) and
this script records them under `steps/<crate>/<module>.snap`, one file per top-level module, so
that parallel branches working on different modules never touch the same snapshot. Other tests
are not recorded.

Usage:
    scripts/steps.py snapshot [--filter P]  # run the probes and (re)write the snapshot files
    scripts/steps.py check    [--filter P]  # run the probes and fail if steps differ from the snapshots
    scripts/steps.py diff     [--filter P]  # run the probes and print a Markdown delta table (never fails)
    scripts/steps.py rank <prefix>          # rank snapshot entries under a test-name prefix (cheapest first)

Options:
    --from-log FILE    parse an existing `snforge test --detailed-resources` log instead of running
    --filter PATTERN   only run / compare / rewrite probes whose name contains PATTERN; with
                       `snapshot`, only the files of modules that appear in the run are rewritten.
                       A PATTERN starting with a crate name (`slingfall_rules`, `slingfall_rules::damage`)
                       runs that crate only.

Runs are always crate-scoped (`snforge test -p <crate>`, one crate after the other; the nested
`crates/slingfall_replay` package from its own directory with `--profile snforge`): never a
workspace-wide test run (AGENTS.md §6).

A probe `crate::module::...::steps_x` belongs to `steps/crate/module.snap`; probes declared directly
in `lib.cairo` (`crate::tests::steps_x`) go to `steps/crate/lib.snap`. Fuzz tests are not recorded.
Only the Python standard library is used so the script runs anywhere CI does.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STEPS_DIR = ROOT / "steps"
PASS_RE = re.compile(r"^\[PASS\]\s+(\S+)\s+\(")
FAIL_RE = re.compile(r"^\[FAIL\]\s+(\S+)")
STEPS_RE = re.compile(r"^steps:\s*(\d+)$")
HEADER = "# Cairo steps per probe, generated by `scripts/steps.py snapshot`. Do not edit by hand.\n"
# Nested packages with their own `[workspace]` (executables, `enable-gas = false`): tested from
# their directory under a gas-enabled profile.
NESTED = {"slingfall_replay": ["--profile", "snforge"]}
SNFORGE_ARGS = ["--tracked-resource", "cairo-steps", "--detailed-resources"]


def crates() -> list[str]:
    return sorted(p.parent.name for p in (ROOT / "crates").glob("*/Scarb.toml"))


def is_probe(test: str) -> bool:
    return test.rsplit("::", 1)[-1].startswith("steps_")


def module_of(test: str) -> tuple[str, str]:
    parts = test.split("::")
    crate = parts[0]
    module = parts[1] if len(parts) > 2 and parts[1] != "tests" else "lib"
    return crate, module


def package_of(pattern: str) -> str | None:
    """The package a `crate::…` filter belongs to (`<crate>_integrationtest` → `<crate>`)."""
    head = pattern.split("::", 1)[0]
    for suffix in ("_integrationtest", "_unittest"):
        if head.endswith(suffix):
            head = head[: -len(suffix)]
    return head if head in crates() else None


def run_crate(crate: str, test_filter: str) -> str:
    if crate in NESTED:
        cmd = ["snforge", "test", *NESTED[crate], *SNFORGE_ARGS, test_filter]
        cwd = ROOT / "crates" / crate
    else:
        cmd = ["snforge", "test", "-p", crate, *SNFORGE_ARGS, test_filter]
        cwd = ROOT
    print(f"$ {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.run(cmd, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        sys.stdout.write(proc.stdout)
        sys.exit(f"error: `{' '.join(cmd)}` exited with {proc.returncode}")
    return proc.stdout


def run_tests(pattern: str | None) -> str:
    package = package_of(pattern) if pattern else None
    if pattern and not package:
        # A bare name filter: every crate, one at a time.
        return "".join(run_crate(c, pattern) for c in crates())
    # A filter that is only a crate name selects the crate's probes (`steps_` in the test name).
    test_filter = pattern if pattern and pattern != package else "steps_"
    return "".join(run_crate(c, test_filter) for c in ([package] if package else crates()))


def parse(log: str) -> dict[str, int]:
    steps: dict[str, int] = {}
    failed = []
    current = None
    for line in log.splitlines():
        line = line.strip()
        if m := PASS_RE.match(line):
            current = m.group(1)
        elif m := FAIL_RE.match(line):
            failed.append(m.group(1))
            current = None
        elif current and (m := STEPS_RE.match(line)):
            if is_probe(current):
                steps[current] = int(m.group(1))
            current = None
    if failed:
        sys.exit("error: failing tests: " + ", ".join(failed))
    return steps


def load_snapshot() -> dict[str, int]:
    entries: dict[str, int] = {}
    for path in sorted(STEPS_DIR.glob("*/*.snap")):
        for line in path.read_text().splitlines():
            if line and not line.startswith("#"):
                name, value = line.rsplit(" ", 1)
                entries[name] = int(value)
    return entries


def write_snapshot(steps: dict[str, int], only_present: bool) -> list[Path]:
    by_file: dict[Path, dict[str, int]] = {}
    for name, value in steps.items():
        crate, module = module_of(name)
        by_file.setdefault(STEPS_DIR / crate / f"{module}.snap", {})[name] = value
    if not only_present:
        for stale in STEPS_DIR.glob("*/*.snap"):
            if stale not in by_file:
                stale.unlink()
    for path, entries in by_file.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + "".join(f"{n} {entries[n]}\n" for n in sorted(entries)))
    return sorted(by_file)


def delta_rows(old: dict[str, int], new: dict[str, int]) -> list[tuple[str, str, str, str]]:
    rows = []
    for name in sorted(old.keys() | new.keys()):
        before, after = old.get(name), new.get(name)
        if before == after:
            continue
        if before is None:
            rows.append((name, "-", str(after), "new"))
        elif after is None:
            rows.append((name, str(before), "-", "removed"))
        else:
            pct = (after - before) / before * 100 if before else 0.0
            rows.append((name, str(before), str(after), f"{after - before:+d} ({pct:+.2f}%)"))
    return rows


def print_table(rows: list[tuple[str, ...]], headers: tuple[str, ...]) -> None:
    print("| " + " | ".join(headers) + " |")
    print("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        print("| " + " | ".join(row) + " |")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["snapshot", "check", "diff", "rank"])
    parser.add_argument("prefix", nargs="?", help="test-name prefix for `rank`")
    parser.add_argument("--from-log", type=Path)
    parser.add_argument("--filter")
    args = parser.parse_args()

    if args.command == "rank":
        entries = {k: v for k, v in load_snapshot().items() if (args.prefix or "") in k}
        ranked = sorted(entries.items(), key=lambda kv: kv[1])
        print_table([(name, str(value)) for name, value in ranked], ("probe", "steps"))
        return

    log = args.from_log.read_text() if args.from_log else run_tests(args.filter)
    new = parse(log)
    if args.filter:
        new = {k: v for k, v in new.items() if args.filter in k}
    if not new:
        sys.exit("error: no `steps_*` probe result found in snforge output (missing --detailed-resources?)")
    old = load_snapshot()

    if args.command == "snapshot":
        if args.filter:
            touched = {module_of(n) for n in new}
            kept = {n: v for n, v in old.items() if module_of(n) in touched and args.filter not in n}
            new = {**kept, **new}
        files = write_snapshot(new, only_present=bool(args.filter))
        print(f"wrote {len(new)} entries to {len(files)} file(s) under {STEPS_DIR.relative_to(ROOT)}/")
        return

    if args.filter:
        old = {k: v for k, v in old.items() if args.filter in k}
    rows = delta_rows(old, new)
    if rows:
        print_table(rows, ("probe", "before", "after", "delta"))
    else:
        print(f"steps snapshot up to date ({len(new)} probes)")
    if args.command == "check" and rows:
        sys.exit("error: Cairo steps drifted from steps/*.snap; run `scripts/steps.py snapshot` and commit the result")


if __name__ == "__main__":
    main()
